version: '3'
services:
  master:
    build: ./master
    volumes:
      - ./:/usr/src/app
     
  agent:
    build: ./agent
    restart: always
    volumes:
      - ./agent:/usr/src/app
    environment:
      - VERBOSE=true
      - API_KEY=$API_KEY
      - SECRET=$SECRET
      - SLACK_URL=$SLACK_URL
    tty: true
